### ISSUE TITLE
Python 3 Python 2 incompatibiliy?

### ISSUE THREAD

**Issue by gharshaw** [preeve9534/venus-signalk-tank-service#1]
I am wanting  to use your venus-signalk-tank-service on my CCGX running firmware v2.80~24. Is it compatible? 
I am getting the following error when running the signaltank.py  on step 4
python3 signalktank.py

Traceback (most recent call last):
  File "signalktank.py", line 29, in <module>
    from vedbus import VeDbusService
  File "/data/venus-signalk-tank-service-main/./ext/velib_python/vedbus.py", line 9, in <module>
    from ve_utils import wrap_dbus_value, unwrap_dbus_value
  File "/data/venus-signalk-tank-service-main/./ext/velib_python/ve_utils.py", line 22
    print 'exit_on_error: there was an exception. Printing stacktrace will be tryed and then exit'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('exit_on_error: there was an exception. Printing stacktrace will be tryed and then exit')?

Thanks for your help

**Comment by gharshaw** [comment]
I was able to get past the error by getting the updated ve_utils.py from the Victron repository

**Comment by gharshaw** [comment]
Can this be used if I do not have a N2K interface from tanks to my CCGX? I have the SeeLevel 709 BT and I am reading the tank data from bluetooth and creating SIgnalK paths with Scott Bender's ' SignalK embedded NodeRed plugin. 

The error I am now getting is 

root@ccgx:/data/venus-signalk-tank-service-main# python3 signalktank.py
Traceback (most recent call last):
  File "signalktank.py", line 202, in <module>
    main()
  File "signalktank.py", line 181, in main
    capacity = jsondata['capacity']['value']
KeyError: 'capacity'


Thanks for your help

**Comment by preeve9534** [comment]
Hi,

I need to dig out my CCGX to look at this - may take a few days to recover it from storage. My recollection is that the software was running on Python 3 on 2.60.

That’s a strange error though, triggered by a standard library import before the script itself starts to do anything.

I have occasionally seen strange behaviour from Python when a shebang script is explicitly started by the target application. I mention this because you say

$> python3 signalktank.py

Rather than

$> ./signalktank.py

PR

**Comment by preeve9534** [comment]
Hi,

Oh that’s interesting.  Looks like the data being injected by NodeRed doesn’t include tank capacity. As you say, I did assume tank injection from N2K sensors which report capacity. Let me look at making that an optional thing.

PR

**Comment by preeve9534** [comment]
OK. I think without access to the exact output format of the data generated by Scott’s NodeRed plugin I’ll be working in the dark and also moving outside the scope of this N2K targeted project.

Since the issue seems to be one of decoding the Signal K tank paths and data it should be straightforward to tweak signalktank.py to work for the data deriving from your hardware / Node Red. You could clone my project (which is in any case a bit of a dead duck since Venus finally provides native support for N2K tanks) and use it as a template for a venus-nodered-tank-service or whatever.

PR

**Comment by gharshaw** [comment]
Appreciate the  feedback - I've made some progress -- Capacity is no longer an issue as I added a tank path for the capacity. 
I understand being a dead duck given the N2K fix 
My next hurdle is this error - Any insight is greatly appreciated
Traceback (most recent call last):
  File "./signalktank.py", line 200, in <module>
    main()
  File "./signalktank.py", line 158, in main
    if fluidtype in N2K_FLUID_TYPES:
NameError: name 'N2K_FLUID_TYPES' is not defined

I have created paths for  fluidtypes 
tanks.greyWater.0.fluidType.value
Should the value be "greyWater" or 2  ?
Does the path seem correct for the fluidtype?

Thank you!,
Gene

**Comment by preeve9534** [comment]
Hi Gene,

N2K derived tank data in SignalK goes way back to the time when data definitions were still in flux. It’s a mess. The N2K derived tank paths have the form.

tanks.fluidTypeName.TankInstance

fluidTypeName was made up by the Signal K developers as a human readable representation of fluid type and the N2K fluid type code was discarded (i.e. not embedded as an actual  data value anywhere). Go figure. In my defence,  did protest at the time. So on my boat I see:

tanks.wasteWater.0

as a SignalK path and that “wasteWater” component of the path is, on legacy systems, the only indication of fluid type. I was lazy, and chose to decode the pathname component since I knew this would work for legacy installations as well as more recent ones where fluid type was available as a real data value. The mapping at line 63 is just a way of getting the N2K fluid type code (that’s required by a Victron tank device) out of the SignalK tank path - you need the number, not the name for dBus.

As for the error - I don’t have an N2K_FLUID_TYPES entity in my code. Did you change the name? Line 63 defines the dictionary that is used to do the decoding described above, but it is called SIGNALK_TO_N2K_FLUID_TYPES.

PR

**Comment by preeve9534** [comment]
My last email might have misled you. Just checked my SignalK install and it seems that the N2K interface still doesn’t inject a data value for fluid type. The only paths I have are like this (and there’s nothing in the meta data either).


> tanks.wasteWater.0.capacity	
> 1.0977999999999999
> m3	12/15 08:41:59	n2k-on-ve.can-socket.88 (127505)
> tanks.wasteWater.0.currentLevel
> 
You can see that in N2K world on Signal K one still has to recover fluid type from the path.

P

**Comment by gharshaw** [comment]
Hi PR,
Thank you for the additional info. I have made some progress as I'm able to get my 1st tank "wasteWater" published on the Dbus. The other two do not. 
SIGNALK_TANKS = [
	{ 'path': 'tanks/wasteWater/0' },
	{ 'path': 'tanks/freshWater/1' },
	{ 'path': 'tanks/greyWater/2' }
	]
 INFO:root:registered ourselves on D-Bus as com.victronenergy.tank.signalk_192_168_10_197_3000_5_0

Can you give me some insight to the comment in your Signalktank app ? "# SignalkTank implements a DBUS service for a single tank"  Is this my issue?

Please forgive my inexperience with coding. I retired from a 20 yr IT career but did little coding -  infrastructure side :-)

Gene

**Comment by gharshaw** [comment]
I've made it happen :-) 
All tanks are published on the CCGX .
My issue was that I had all the tank paths on SignalK as .0 Updated each tank respectively to  0,1,& 2
"tanks.freshWater.0.currentLevel"
"tanks.wasteWater.1.currentLevel"
"tanks.greyWater.2.currentLevel"

I also updated the "import gobject" to " from gi.repository import GLib" and updated gobject methods to GLib. I referenced this from the updated velib_python/dbusdummyservice.py script

Thanks for the code. 💯 

Gene

**Comment by preeve9534** [comment]
Oh that is so good. Well done!

I spent today rebuilding my domestic panel, so went a little quiet! Sorry.
My wife was ecstatic when I finally got our tank data on our old CCGX ...
And then just a year later Victron finally caught up!

Enjoy.

Paul
